name: Build and Publish Hotkey Server

on:
  push:
    paths:
      - 'hotkey-server/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[NO-BUILD]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure git user
        run: |
          git config --global user.email "dakota.bourne0210@gmail.com"
          git config --global user.name "Git Actions"
          echo "TAG=$(npm version patch)" >> $GITHUB_ENV
      - name: Setup node environment
        run: |
          cd hotkey-server
          npm config set registry https://registry.npmjs.org/
          npm install --production
      - name: Handle versioning
        run: |
          cd hotkey-server
          git add . && git commit -m "[NO-BUILD] Bump version to $TAG" && git tag "$TAG" && git push && git push --tags
      - name: Build server executable
        run: |
          cd hotkey-server
          npm run build-windows
      - name: Create release with binary asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: 'hotkey-server-v$TAG'
        with:
          files: hotkey-server/dist/server.exe