name: Build and Publish Hotkey Server

on:
  push:
    paths:
      - 'hotkey-server/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[NO-BUILD]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          echo "TAG=$(npm version patch)" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.RELEASE_TOKEN }}" >> $GITHUB_ENV
      - name: Setup node environment
        run: |
          cd hotkey-server
          npm install --production
      - name: Handle versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git push origin main --tags
      - name: Build server executable
        run: |
          cd hotkey-server
          npm run build-windows
      - name: Create release with binary asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: 'hotkey-server-v$TAG'
        with:
          files: hotkey-server/dist/server.exe