name: Build and Publish Hotkey Server

on:
  push:
    paths:
      - 'hotkey-server/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node environment
        run: |
          cd hotkey-server
          npm config set registry https://registry.npmjs.org/
          npm install --production
      - name: Handle versioning
        run: |
          cd hotkey-server
          npm version patch && git add . && git commit -m "Bump version to $(npm version)" && git tag "$(npm version)"
      - name: Build server executable
        run: |
          cd hotkey-server
          npm run build-windows
      - name: Create release with binary asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: 'hotkey-server-v$(npm version)'
        with:
          files: dist/server.exe